# Generated by Django 5.0.6 on 2024-06-25 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1)),
                ('citizenship', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('snils', models.CharField(max_length=20)),
                ('study_direction_code', models.CharField(max_length=20)),
                ('study_direction_name', models.CharField(max_length=200)),
                ('study_direction_profile', models.CharField(max_length=200)),
                ('enrollment_year', models.IntegerField()),
                ('graduation_year', models.IntegerField()),
                ('education_form', models.CharField(choices=[('Full-time', 'Очная'), ('Part-time', 'Заочная')], max_length=20)),
                ('employment_book', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_status', models.CharField(max_length=200)),
                ('change_date', models.DateField()),
                ('graduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.graduate')),
            ],
        ),
    ]
