# Generated by Django 5.0.6 on 2024-07-02 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('students', '0003_alter_employmenthistory_employment_placework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmenthistory',
            name='employment_placework',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Место работы'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='employment_status',
            field=models.CharField(default='Безработный', max_length=40, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='graduate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.graduate', verbose_name='Выпускник'),
        ),
    ]
