# Generated by Django 5.0.6 on 2024-07-03 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_inn_company_okved'),
        ('students', '0005_alter_employmenthistory_employment_placework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmenthistory',
            name='employment_placework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company', verbose_name='Место работы'),
        ),
    ]
