# Generated by Django 5.0.6 on 2024-07-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название предприятия')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес предприятия')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона предприятия')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail предприятия')),
                ('website', models.URLField(verbose_name='Сайт предприятия')),
            ],
            options={
                'verbose_name': 'Предприятие',
                'verbose_name_plural': 'Предприятия',
            },
        ),
    ]
