# Generated by Django 5.0.6 on 2024-07-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='inn',
            field=models.CharField(default='Безработный', max_length=12, verbose_name='ИНН предприятия'),
        ),
        migrations.AddField(
            model_name='company',
            name='okved',
            field=models.CharField(default='Безработный', max_length=30, verbose_name='ОКВЭД предприятия'),
        ),
    ]
